workspace(name = "poe-groups")

load("//:build_deps.bzl", "build_deps")
build_deps()

load("@io_bazel_rules_scala//:version.bzl", "bazel_version")

bazel_version(name = "bazel_version")

load("@io_bazel_rules_scala//scala:scala.bzl", "scala_repositories")
load("//:scala_version.bzl", "scala_version")

register_toolchains("//toolchains:main-scala_toolchain")

scala_repositories((
    scala_version,
    {
        "scala_compiler": "cedc3b9c39d215a9a3ffc0cc75a1d784b51e9edc7f13051a1b4ad5ae22cfbc0c",
        "scala_library": "0a57044d10895f8d3dd66ad4286891f607169d948845ac51e17b4c1cf0ab569d",
        "scala_reflect": "56b609e1bab9144fb51525bfa01ccd72028154fc40a58685a1e9adcbe7835730",
    },
))

load("//:third_party.bzl", "dependencies")

dependencies()
